### ISSUE TITLE
put uploads folder outside webroot

### ISSUE THREAD

**Issue by michielbdejong** [ehdr/docker-known#3]
in the install instructions it says the uploads folder should be www-data-writable and outside the webroot. seems that this Dockerfile puts it in /app/known/uploads which seems to be inside the webroot? I guess this has some security implications (self-xss maybe or something)

**Comment by ehdr** [comment]
Good point, thanks @michielbdejong! It's probably far from the last thing in this image that has security implications... ;) But I appreciate the help in hunting them down!
